version: '3.11'
services:
  dashboard:
    image: python:3.11
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=${REDIS_URL-redis://redis:6379}
      - FASTAPI_PORT=${FASTAPI_PORT-8000}
    ports:
      - '${FASTAPI_PORT-8000}:8000'
    command:
      [
        'sh',
        '-c',
        'uvicorn --host 0.0.0.0 --port ${FASTAPI_PORT-8000} app:app --reload',
      ]
